### ISSUE TITLE
Просьба переименовать файлы по порядку

### ISSUE THREAD

**Issue by fox0** [qrdl/fizzbuzz#2]
Например, так:
01-supernaive.c
02-naive.c
03-unrolled.c
итд

**Comment by qrdl** [comment]
Я понимаю смысл этого запроса, но мне не кажется, что это вот прям нужно, тем более что я не исключаю, что в дальнейшем я добавлю еще какие-то имплементации, может даже промежуточные, и тогда все переименовывать?

**Comment by fox0** [comment]
А так?
00-supernaive.c
10-naive.c
20-unrolled.c
...

**Comment by qrdl** [comment]
Так, пожалуй, будет лучше. Я подумаю. Не обещаю, что сделаю, но подумаю про это.
