### ISSUE TITLE
Supernaive needs to be re-measured.

### ISSUE THREAD

**Issue by kariya-mitsuru** [qrdl/fizzbuzz#7]
Supernaive has reduced the amount of output due to pull request #3 by @mattn, so I think it is better to be re-measured.

cf. My machine's results.

```
supernaive 91.526s
naive      61.591s
```

**Comment by qrdl** [comment]
Good point, will do

**Comment by qrdl** [comment]
Fixed version is much faster, README updated. Thanks for spotting it!
